#!/bin/bash
cd ../3p0
root -q ../plotit/plotallmomprofiles.C'("Jam1_3GeV_b0-14_RQMDRMF_NS2_all_bcut0_14_ana7_hist.root",0.,5.)'
cd ../2p4
root -q ../plotit/plotallmomprofiles.C'("Jam1_2p4GeV_b0-14_RQMDRMF_NS2_all_bcut0_14_ana7_hist.root",0.,5.)'
cd ../3p2
root -q ../plotit/plotallmomprofiles.C'("Jam1_3p2GeV_b0-14_RQMDRMF_NS2_all_bcut0_14_ana7_hist.root",0.,5.)'
cd ../3p5
root -q ../plotit/plotallmomprofiles.C'("Jam1_3p5GeV_b0-14_RQMDRMF_NS2_all_bcut0_14_ana7_hist.root",0.,5.)'
cd ../3p9
root -q ../plotit/plotallmomprofiles.C'("Jam1_3p9GeV_b0-14_RQMDRMF_NS2_all_bcut0_14_ana7_hist.root",0.,5.)'
cd ../4p5
root -q ../plotit/plotallmomprofiles.C'("Jam1_4p5GeV_b0-14_RQMDRMF_NS2_all_bcut0_14_ana7_hist.root",0.,5.)'
cd ../3p0cascade
root -q ../plotit/plotallmomprofiles.C'("Jam1_3GeV_b0-14_cascade1M_all_bcut0_14_ana7_hist.root",0.,5.)'

#root -q ../plotit/plotallmomprofiles.C'("Jam1_3GeV_b0-14_RQMDRMF_NS2_all_bcut0_14_ana7_hist.root",0.,5.)'
